version: '3.8'

services:
  # Flask app container
  flask_app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  # PostgreSQL database container
  postgres:
    image: postgres:latest
    container_name: production-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5430:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
